[Improvement] - readme
betrybe/sd-0x-trybeer pull request #10
Opened 2021-01-12 13:29 UTC by LizzardMedeiros

Melhorias e implementações referentes à [Sprint](https://github.com/betrybe/course/issues/2543)

Closes https://github.com/betrybe/course/issues/2637

2021-01-13 10:37 UTC, nato-re approved these changes
Bom trabalho, Lizz!

2021-01-13 10:37 UTC, nato-re commented on README.md
> +- Será validado que ao clicar no menu meus perfil será redirecionado para tela de meus perfil
```suggestion
- Será validado que ao clicar no menu perfil será redirecionado para tela de perfil
```

2021-01-13 10:37 UTC, nato-re commented on README.md
> +- Será validado que o status do pedido fique marcado como entregue como na imagem abaixo:
```suggestion
- Será validado que o status do pedido fica marcado como entregue como na imagem abaixo:
```

2021-01-13 10:37 UTC, nato-re commented on README.md
> +- Será validado que o status do pedido fique marcado como entregue como na imagem abaixo:
```suggestion
- Será validado que o status do pedido fica marcado como entregue como na imagem abaixo:
```

2021-01-29 14:12 UTC, phelipe-ohlsen approved these changes

2021-02-02 15:32 UTC, roziscoding approved these changes

2021-03-10 15:11 UTC, renatosousafilho commented on README.md
> +    `Cliente:`
Tá meio confuso isso, acho que podemos tirar isso daqui e deixar só `Requisitos Entrega 1:` e `Requisitos Entrega 2:`

2021-03-10 16:21 UTC, renatosousafilho commented on README.md
> +- Será validado que ao clicar no menu meus perfil será redirecionado para tela de meus perfil
```suggestion
- Será validado que ao clicar no menu `meu perfil` será redirecionado para tela de `meu perfil`
```

2021-03-10 16:22 UTC, renatosousafilho commented on front-end/package.json
> +    "lint:styles": "npx stylelint '**/*.css'"
@roziscoding @brunobatista25 isso vai dar alguma treta com as alterações do ESLint que foram feitas recentemente?

2021-03-10 16:23 UTC, renatosousafilho commented on README.md
>  O não cumprimento de um requisito, total ou parcialmente, impactará em sua avaliação.
```suggestion
O não cumprimento de um requisito, total ou parcialmente, impactará na sua avaliação.
```

2021-03-10 16:27 UTC, renatosousafilho commented on README.md
> +#### ⚠️ Leia-os atentamente e siga à risca o que for pedido. ⚠️
Fiz um commit corrigindo esses pontos. Obrigado @phelipe-ohlsen

2021-03-10 17:04 UTC, brunobatista25 requested changes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que é possível acessar a tela de registro
alterando esses caras e preciso alterar os its dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que ao clicar no menu `meu perfil` será redirecionado para tela de `meu perfil`
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que contém os atributos descritos no protótipo
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que não é possível fazer o registro com um nome com caracteres especiais
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que não é possível fazer o registro com um nome com menos de 12 letras
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que não é possível fazer login com um email inválido
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que não é possível fazer login com um email já existente
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que não é possível fazer login com uma senha em branco
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que não é possível fazer login com uma senha com menos de 6 caracteres
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que é possível fazer cadastro de um admin com sucesso e ser redirecionado para tela do admin
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que é possível acessar a tela do detalhe do pedido do administrador
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que contém os atributos descritos no protótipo
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que o pedido contém nome e status do pedido
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que o pedido contém todos os detalhes do pedido
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que o pedido com status pendente irá apresentar na tela o botão "Marcar como entregue"
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on README.md
> +- Será validado que o pedido ao marcar como entregue o status mude para entregue" e o botão nao esteja mais visível
aqui nesses caras tbm tem que alterar os its tbm dos testes

2021-03-10 17:04 UTC, brunobatista25 commented on front-end/package.json
> +    "lint:styles": "npx stylelint '**/*.css'"
isso ta correto, vai dar treta nao

2021-03-11 00:44 UTC, renatosousafilho commented on README.md
> +- Será validado que não é possível fazer o registro com um nome com números
Está ok nos dois repos

2021-03-11 00:44 UTC, renatosousafilho commented on README.md
> +- Será validado que não é possível fazer login com um email já existente
Está ok nos dois repos

2021-03-11 00:45 UTC, renatosousafilho commented on README.md
> +- Será validado que não é possível fazer login com uma senha em branco
Está ok nos dois repos

2021-03-11 00:45 UTC, renatosousafilho commented on README.md
> +- Será validado que não é possível fazer login com uma senha com menos de 6 caracteres
Está ok nos dois repos

2021-03-11 00:46 UTC, renatosousafilho commented on README.md
> +- Será validado que é possível fazer cadastro de um admin com sucesso e ser redirecionado para tela do admin
Está ok nos dois repos

2021-03-11 00:51 UTC, renatosousafilho commented on README.md
> +- Será validado que ao clicar no menu `meu perfil` será redirecionado para tela de `meu perfil`
Vou alterar e padronizar para ficar assim: `Será validado que ao clicar no menu Perfil será redirecionado para tela de Perfil`

Faz mais sentido com o que está no figma

2021-03-11 00:52 UTC, renatosousafilho commented on README.md
> +- Será validado que é possível acessar a tela do detalhe do pedido do administrador
ok nos dois repos

2021-03-11 00:52 UTC, renatosousafilho commented on README.md
> +- Será validado que contém os atributos descritos no protótipo
ok nos dois repos

2021-03-11 00:53 UTC, renatosousafilho commented on README.md
> +- Será validado que o pedido contém nome e status do pedido
ok nos dois repos

2021-03-11 00:54 UTC, renatosousafilho commented on README.md
> +- Será validado que o pedido com status pendente irá apresentar na tela o botão "Marcar como entregue"
Ok nos dois repos

2021-03-11 00:55 UTC, renatosousafilho commented on README.md
> +- Será validado que o pedido ao marcar como entregue o status mude para entregue" e o botão nao esteja mais visível
ok nos dois repos

2021-03-11 01:02 UTC, renatosousafilho commented on cypress/integration/menuAdmin.spec.js
> +  it('Será validado que ao clicar no menu Perfil será redirecionado para tela de Perfil', () => {
@brunobatista25 o único it que precisei modificar no repo de teste foi esse aqui. E eu não tenho permissão para abrir PR nesse repo.

2021-03-11 01:02 UTC, renatosousafilho reviewed
Detalhe final sobre it

2021-03-11 01:16 UTC, renatosousafilho commented on README.md
> +- Será validado que não é possível fazer o registro com um nome com caracteres especiais
Está ok nos dois repos

2021-03-11 01:39 UTC, merged