Faz o eslint cobrir arquivos .jsx também
betrybe/sd-0x-trybeer pull request #12
Opened 2021-01-20 00:16 UTC by barraponto

2021-02-03 18:48 UTC, albertosca requested changes
Só isso não funciona! ❌ 

O negócio é que esse comando roda localmente, mas o avaliador do projeto não usa essa config. Pra que ele não ignore os `jsx` a action dele no `.github/workflows/main.yml` tem que estar na [v2.1](https://github.com/betrybe/eslint-linter-action/releases/tag/v2.1).

2021-02-03 19:28 UTC, roziscoding commented
@barraponto consegue fazer essa alteração que o @albertosca comentou ?

2021-02-09 21:25 UTC, barraponto commented
este PR é sobre o lint pro estudante mesmo.
o bump da versão do avaliador pode ter altas consequências, não? não faz sentido ter um PR só pra esse bump?

2021-02-09 22:55 UTC, roziscoding commented
@barraponto especificamente essa versão tem esse único impacto de alterar quais arquivos são considerados pelo ESLint :)

2021-02-12 19:29 UTC, albertosca approved these changes
@barraponto Rola de colocar o `serviceWorker` no .gitignore?

2021-02-23 15:38 UTC, barraponto commented
@albertosca adicionei no `./frontend/.eslintignore`, acho que era isso que vc quis dizer, não?

confesso que fiquei surpreso que o *evaluator* respeitou as configurações de eslint do projeto.
um estudante espertinho pode colocar `*` no `.eslintignore` se ele quiser ver os testes rodando e só alinhar o eslint depois dos requisitos passarem...

2021-03-04 18:51 UTC, roziscoding approved these changes

2021-03-12 16:11 UTC, barraponto commented
todas as coisas que a gente discutiu já foram mergeadas:

* adicionar o .jsx no eslintrc entrou em #10 
* ignorar serviceworker.js no eslintignore entrou em #14 

não sei se devo dar merge nesse branch (que agora só muda a versão do evaluator) ou se a gente vai estar atravessando um outro PR que foca especificamente no evaluator. mas como Post Mortem de todo esse trabalho duplicado, eu queria pedir pra gente focar em _uma coisa por PR_.

2021-03-12 17:26 UTC, albertosca commented
@barraponto Esse seu comentário passou batido pelo meu radar, bicho! Falha minha. Mas assim, é importante atualizarmos a versão do avaliador e proponho mergearmos já esse PR, ela garante além de qualquer dúvida que os `.jsx` então sendo contemplados.

Sobre o `.eslintignore`, isso pode acontecer mesmo, a pessoa pode colocar um `*` ali e boa, aprovação. Mas se isso não for desfeito é violação de honestidade intelectual.

De resto, de acordo com a saída! O famoso "vamos mergear esse aqui e abrir outro". Na nossa rotina tão intensa isso permite que não percamos trabalho por sermos atropelados por novas circunstâncias, deixando algum PR desses pra trás.

2021-03-12 18:04 UTC, merged

2021-03-12 18:05 UTC, barraponto commented
atualizei o título pra facilitar o dia que a gente quiser encontrar este PR de novo.