Adicionando observação sobre Trybeer v2
betrybe/sd-0x-trybeer pull request #19
Opened 2021-03-08 20:42 UTC by renatosousafilho

2021-03-09 02:38 UTC, antoniosb commented on README.md
> +### Importante
```suggestion
---

### IMPORTANTE ⚠️ 
```

2021-03-09 02:38 UTC, antoniosb commented on README.md
> +O projeto Trybeer v1 é base para o projeto Trybeer v2, portanto, o cumprimento de 100% dos requisitos obrigatórios desse projeto (Trybeer v1) é um pré-requisito para o projeto Trybeer v2. O grupo pre
```suggestion
* O projeto TryBeer é a base para o desenvolvimento projeto TryBeer **v2**;

* Portanto, **o cumprimento de 100% dos requisitos obrigatórios desse projeto** (TryBeer) é um pré-requisito para o projeto **TryBeer v2**;

* O grupo precisa estar ciente que a não realização de todos os requisitos _(mesmo que o cumprimento pelo menos 80% dos requisitos obrigatórios para garantir a aprovação antes do prazo para entrar em recuperação, ou 90% dos requisitos totais depois do prazo)_, impactará na entrega do **TryBeer v2**;

* O prazo disponível para esse projeto contempla o tempo previsto para atingir o objetivo de concluir 100% dos requisitos obrigatórios;

* Dessa forma, o grupo terá todas as condições para chegar ao projeto **TryBeer v2** com o código preparado _(100% dos requisitos obrigatórios deste projeto)_ para iniciar o desenvolvimento dos seus requisitos.
```

2021-03-10 11:15 UTC, LucasCFerraz requested changes

2021-03-10 11:15 UTC, LucasCFerraz commented on README.md
> +* O projeto TryBeer é a base para o desenvolvimento projeto TryBeer **v2**;
```suggestion
* O projeto TryBeer é a base para o desenvolvimento do projeto TryBeer **v2**;
```

2021-03-10 13:56 UTC, antoniosb approved these changes

2021-03-10 14:41 UTC, merged